#include <rpc_types.idl>

module robot {

module abc {

  	interface B
    {
      void bla();
    }; 

};

enum Command { START_COMMAND, STOP_COMMAND };

struct Status 
{
  string msg;
};

interface A 
{
  void greet();
};

interface RobotControl 
{
  void  getStatus(out Status status);
  void  command(Command com);
  float setSpeed(float speed);
  float getSpeed();
};

}