/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: robot.h
  Source: robot.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"
#include "rpc_types.h"

#ifndef _DDSL_ROBOT_H_
#define _DDSL_ROBOT_H_


#ifdef __cplusplus
extern "C" {
#endif

typedef enum robot_Command
{
  robot_START_COMMAND,
  robot_STOP_COMMAND
} robot_Command;

#define robot_Command__alloc() \
((robot_Command*) dds_alloc (sizeof (robot_Command)));


typedef struct robot_Status
{
  char * msg;
} robot_Status;





typedef struct robot_TooFast
{
  dds_rpc_UnusedMember dummy;
} robot_TooFast;



typedef struct robot_RobotControl_command_In
{
  robot_Command com;
} robot_RobotControl_command_In;



typedef struct robot_RobotControl_setSpeed_In
{
  float speed;
} robot_RobotControl_setSpeed_In;



typedef struct robot_RobotControl_getSpeed_In
{
  dds_rpc_UnusedMember dummy;
} robot_RobotControl_getSpeed_In;



typedef struct robot_RobotControl_getStatus_In
{
  dds_rpc_UnusedMember dummy;
} robot_RobotControl_getStatus_In;


#define robot_RobotControl_command_Hash 1
#define robot_RobotControl_setSpeed_Hash 2
#define robot_RobotControl_getSpeed_Hash 3
#define robot_RobotControl_getStatus_Hash 4


typedef struct robot_RobotControl_Call
{
  int32_t _d;
  union
  {
    dds_rpc_UnknownOperation unknownOp;
    robot_RobotControl_command_In command;
    robot_RobotControl_setSpeed_In setSpeed;
    robot_RobotControl_getSpeed_In getSpeed;
    robot_RobotControl_getStatus_In getStatus;
  } _u;
} robot_RobotControl_Call;

#define robot_RobotControl_Call__alloc() \
((robot_RobotControl_Call*) dds_alloc (sizeof (robot_RobotControl_Call)));


typedef struct robot_RobotControl_Request
{
  dds_rpc_RequestHeader header;
  robot_RobotControl_Call data;
} robot_RobotControl_Request;



typedef struct robot_RobotControl_command_Out
{
  dds_rpc_UnusedMember dummy;
} robot_RobotControl_command_Out;



typedef struct robot_RobotControl_setSpeed_Out
{
  float return_;
} robot_RobotControl_setSpeed_Out;



typedef struct robot_RobotControl_getSpeed_Out
{
  float return_;
} robot_RobotControl_getSpeed_Out;


#define robot_TooFast_Ex_Hash 45037


typedef struct robot_RobotControl_getStatus_Out
{
  robot_Status status;
} robot_RobotControl_getStatus_Out;



typedef struct robot_RobotControl_command_Result
{
  int32_t _d;
  union
  {
    dds_rpc_UnknownException unknownEx;
    robot_RobotControl_command_Out result;
  } _u;
} robot_RobotControl_command_Result;

#define robot_RobotControl_command_Result__alloc() \
((robot_RobotControl_command_Result*) dds_alloc (sizeof (robot_RobotControl_command_Result)));


typedef struct robot_RobotControl_setSpeed_Result
{
  int32_t _d;
  union
  {
    dds_rpc_UnknownException unknownEx;
    robot_RobotControl_setSpeed_Out result;
    robot_TooFast toofast_ex;
  } _u;
} robot_RobotControl_setSpeed_Result;

#define robot_RobotControl_setSpeed_Result__alloc() \
((robot_RobotControl_setSpeed_Result*) dds_alloc (sizeof (robot_RobotControl_setSpeed_Result)));


typedef struct robot_RobotControl_getSpeed_Result
{
  int32_t _d;
  union
  {
    dds_rpc_UnknownException unknownEx;
    robot_RobotControl_getSpeed_Out result;
  } _u;
} robot_RobotControl_getSpeed_Result;

#define robot_RobotControl_getSpeed_Result__alloc() \
((robot_RobotControl_getSpeed_Result*) dds_alloc (sizeof (robot_RobotControl_getSpeed_Result)));


typedef struct robot_RobotControl_getStatus_Result
{
  int32_t _d;
  union
  {
    dds_rpc_UnknownException unknownEx;
    robot_RobotControl_getStatus_Out result;
  } _u;
} robot_RobotControl_getStatus_Result;

#define robot_RobotControl_getStatus_Result__alloc() \
((robot_RobotControl_getStatus_Result*) dds_alloc (sizeof (robot_RobotControl_getStatus_Result)));


typedef struct robot_RobotControl_Return
{
  int32_t _d;
  union
  {
    dds_rpc_UnknownOperation unknownOp;
    robot_RobotControl_command_Result command;
    robot_RobotControl_setSpeed_Result setSpeed;
    robot_RobotControl_getSpeed_Result getSpeed;
    robot_RobotControl_getStatus_Result getStatus;
  } _u;
} robot_RobotControl_Return;

#define robot_RobotControl_Return__alloc() \
((robot_RobotControl_Return*) dds_alloc (sizeof (robot_RobotControl_Return)));


typedef struct robot_RobotControl_Reply
{
  dds_rpc_ReplyHeader header;
  robot_RobotControl_Return data;
} robot_RobotControl_Reply;


#ifdef __cplusplus
}
#endif
#endif /* _DDSL_ROBOT_H_ */
