/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: robot.c
  Source: robot.idl
  Cyclone DDS: V0.7.0

*****************************************************************/
#include "robot.h"














