/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: rpc_types.c
  Source: rpc_types.idl
  Cyclone DDS: V0.7.0

*****************************************************************/
#include "rpc_types.h"







