/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: rpc_types.h
  Source: rpc_types.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_RPC_TYPES_H_
#define _DDSL_RPC_TYPES_H_


#ifdef __cplusplus
extern "C" {
#endif

typedef uint8_t dds_GuidPrefix_t [12];

#define dds_GuidPrefix_t__alloc() \
((dds_GuidPrefix_t*) dds_alloc (sizeof (dds_GuidPrefix_t)));


typedef struct dds_EntityId_t
{
  uint8_t entityKey[3];
  uint8_t entityKind;
} dds_EntityId_t;



typedef struct dds_GUID_t
{
  dds_GuidPrefix_t guidPrefix;
  dds_EntityId_t entityId;
} dds_GUID_t;



typedef struct dds_SequenceNumber_t
{
  int32_t high;
  uint32_t low;
} dds_SequenceNumber_t;



typedef struct dds_SampleIdentity
{
  dds_GUID_t writer_guid;
  dds_SequenceNumber_t sequence_number;
} dds_SampleIdentity;


typedef uint8_t dds_rpc_UnknownOperation ;

#define dds_rpc_UnknownOperation__alloc() \
((dds_rpc_UnknownOperation*) dds_alloc (sizeof (dds_rpc_UnknownOperation)));
typedef uint8_t dds_rpc_UnknownException ;

#define dds_rpc_UnknownException__alloc() \
((dds_rpc_UnknownException*) dds_alloc (sizeof (dds_rpc_UnknownException)));
typedef uint8_t dds_rpc_UnusedMember ;

#define dds_rpc_UnusedMember__alloc() \
((dds_rpc_UnusedMember*) dds_alloc (sizeof (dds_rpc_UnusedMember)));
typedef enum dds_rpc_RemoteExceptionCode_t
{
  dds_rpc_REMOTE_EX_OK,
  dds_rpc_REMOTE_EX_UNSUPPORTED,
  dds_rpc_REMOTE_EX_INVALID_ARGUMENT,
  dds_rpc_REMOTE_EX_OUT_OF_RESOURCES,
  dds_rpc_REMOTE_EX_UNKNOWN_OPERATION,
  dds_rpc_REMOTE_EX_UNKNOWN_EXCEPTION
} dds_rpc_RemoteExceptionCode_t;

#define dds_rpc_RemoteExceptionCode_t__alloc() \
((dds_rpc_RemoteExceptionCode_t*) dds_alloc (sizeof (dds_rpc_RemoteExceptionCode_t)));
typedef char dds_rpc_InstanceName [256];

#define dds_rpc_InstanceName__alloc() \
((dds_rpc_InstanceName*) dds_alloc (sizeof (dds_rpc_InstanceName)));


typedef struct dds_rpc_RequestHeader
{
  dds_SampleIdentity requestId;
  dds_rpc_InstanceName instanceName;
} dds_rpc_RequestHeader;



typedef struct dds_rpc_ReplyHeader
{
  dds_SampleIdentity relatedRequestId;
  dds_rpc_RemoteExceptionCode_t remoteEx;
} dds_rpc_ReplyHeader;


#ifdef __cplusplus
}
#endif
#endif /* _DDSL_RPC_TYPES_H_ */
